const ActionTypes = {
    LOADER: 'LOADER',
    SHOWERROR: 'SHOWERROR',
    HIDEERROR: 'HIDEERROR',
    EMAILCREDENTIALS: 'EMAILCREDENTIALS',
    // GOOGLECREDENTIAL:'GOOGLECREDENTIAL',
    SOCIALCREDENTIALS: 'SOCIALCREDENTIALS',
    CLEARSTATE: 'CLEARSTATE',
    CLEARCHAT: 'CLEARCHAT',
    GETCHEFS: 'GETCHEFS',
    CAROUSELINDEX: 'CAROUSELINDEX',
    CLEARREDUXSTATE: 'CLEARREDUXSTATE',
    GETCHATS: 'GETCHATS',
    CURRENTLOC: 'CURRENTLOC',
    ACTIVESESSION: 'ACTIVESESSION',
    CLEARSESSIONS: 'CLEARSESSIONS',
    ROLES: 'ROLES',
    ORDERDETAILS: 'ORDERDETAILS',
    CLEARROLES: 'CLEARROLES',
    ORDERDETAILSCLEAR: 'ORDERDETAILSCLEAR',
}

export default ActionTypes;